INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'亚托克斯'),
	 (1,'阿狸'),
	 (1,'阿卡丽'),
	 (1,'阿克尚'),
	 (1,'阿利斯塔'),
	 (1,'阿木木'),
	 (1,'艾尼维亚'),
	 (1,'安妮'),
	 (1,'厄斐琉斯'),
	 (1,'艾希');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'奥瑞利安·索尔'),
	 (1,'阿萝拉'),
	 (1,'阿兹尔'),
	 (1,'巴德'),
	 (1,'卑尔维斯'),
	 (1,'布里茨'),
	 (1,'布兰德'),
	 (1,'布隆'),
	 (1,'贝蕾亚'),
	 (1,'凯特琳');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'卡蜜尔'),
	 (1,'卡西奥佩娅'),
	 (1,'科加斯'),
	 (1,'库奇'),
	 (1,'德莱厄斯'),
	 (1,'黛安娜'),
	 (1,'德莱文'),
	 (1,'蒙多医生'),
	 (1,'艾克'),
	 (1,'伊莉丝');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'伊芙琳'),
	 (1,'伊泽瑞尔'),
	 (1,'费德提克'),
	 (1,'菲奥娜'),
	 (1,'菲兹'),
	 (1,'加里奥'),
	 (1,'普朗克'),
	 (1,'盖伦'),
	 (1,'纳尔'),
	 (1,'古拉加斯');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'格雷福斯'),
	 (1,'格温'),
	 (1,'赫卡里姆'),
	 (1,'黑默丁格'),
	 (1,'彗'),
	 (1,'俄洛伊'),
	 (1,'艾瑞莉娅'),
	 (1,'艾翁'),
	 (1,'迦娜'),
	 (1,'嘉文四世');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'贾克斯'),
	 (1,'杰斯'),
	 (1,'烬'),
	 (1,'金克丝'),
	 (1,'卡莎'),
	 (1,'卡莉丝塔'),
	 (1,'卡尔玛'),
	 (1,'卡尔萨斯'),
	 (1,'卡萨丁'),
	 (1,'卡特琳娜');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'凯尔'),
	 (1,'凯隐'),
	 (1,'凯南'),
	 (1,'卡兹克'),
	 (1,'千珏'),
	 (1,'克烈'),
	 (1,'克格莫'),
	 (1,'奎桑提'),
	 (1,'乐芙兰'),
	 (1,'李青');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'蕾欧娜'),
	 (1,'莉莉娅'),
	 (1,'丽桑卓'),
	 (1,'卢锡安'),
	 (1,'璐璐'),
	 (1,'拉克丝'),
	 (1,'墨菲特'),
	 (1,'玛尔扎哈'),
	 (1,'茂凯'),
	 (1,'易');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'米利欧'),
	 (1,'厄运小姐'),
	 (1,'孙悟空'),
	 (1,'莫德凯撒'),
	 (1,'莫甘娜'),
	 (1,'纳亚菲利'),
	 (1,'娜美'),
	 (1,'内瑟斯'),
	 (1,'诺提勒斯'),
	 (1,'妮蔻');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'奈德丽'),
	 (1,'尼菈'),
	 (1,'魔腾'),
	 (1,'努努和威朗普'),
	 (1,'奥拉夫'),
	 (1,'奥莉安娜'),
	 (1,'奥恩'),
	 (1,'潘森'),
	 (1,'波比'),
	 (1,'派克');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'奇亚娜'),
	 (1,'奎因'),
	 (1,'洛'),
	 (1,'拉莫斯'),
	 (1,'雷克塞'),
	 (1,'芮尔'),
	 (1,'烈娜塔 · 戈拉斯克'),
	 (1,'雷克顿'),
	 (1,'雷恩加尔'),
	 (1,'锐雯');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'兰博'),
	 (1,'瑞兹'),
	 (1,'莎弥拉'),
	 (1,'瑟庄妮'),
	 (1,'赛娜'),
	 (1,'萨勒芬妮'),
	 (1,'瑟提'),
	 (1,'萨科'),
	 (1,'慎'),
	 (1,'希瓦娜');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'辛吉德'),
	 (1,'赛恩'),
	 (1,'希维尔'),
	 (1,'斯卡纳'),
	 (1,'斯莫德'),
	 (1,'娑娜'),
	 (1,'索拉卡'),
	 (1,'斯维因'),
	 (1,'塞拉斯'),
	 (1,'辛德拉');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'塔姆'),
	 (1,'塔莉垭'),
	 (1,'泰隆'),
	 (1,'塔里克'),
	 (1,'提莫'),
	 (1,'锤石'),
	 (1,'崔丝塔娜'),
	 (1,'特朗德尔'),
	 (1,'泰达米尔'),
	 (1,'崔斯特');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'图奇'),
	 (1,'乌迪尔'),
	 (1,'厄加特'),
	 (1,'韦鲁斯'),
	 (1,'薇恩'),
	 (1,'维迦'),
	 (1,'维克兹'),
	 (1,'薇古丝'),
	 (1,'蔚'),
	 (1,'佛耶戈');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'维克托'),
	 (1,'弗拉基米尔'),
	 (1,'沃利贝尔'),
	 (1,'沃里克'),
	 (1,'霞'),
	 (1,'泽拉斯'),
	 (1,'赵信'),
	 (1,'亚索'),
	 (1,'永恩'),
	 (1,'约里克');
INSERT INTO default_table.indiv_name (language_id,indiv_name) VALUES
	 (1,'悠米'),
	 (1,'扎克'),
	 (1,'劫'),
	 (1,'泽丽'),
	 (1,'吉格斯'),
	 (1,'基兰'),
	 (1,'佐伊'),
	 (1,'婕拉');
